# db.py - Compatibility layer for backward compatibility
# This module re-exports all functions from db_enhanced for scrapers and legacy code

from db_enhanced import (
    # Database initialization
    init_db,
    close_database,
    get_pool,
    
    # User management
    get_user_by_username,
    get_user_by_email,
    create_user_db,
    update_user_login,
    update_user_login_and_log_activity,
    get_all_users,
    get_all_user_emails,
    get_user_count,
    update_user_role,
    deactivate_user,
    create_support_ticket,
    get_support_ticket,
    list_support_tickets,
    add_support_ticket_event,
    list_support_ticket_events,
    update_support_ticket,
    get_support_metrics,
    export_user_data,
    purge_user_data,
    
    # Email verification and password reset
    create_verification_token,
    verify_email_token,
    create_password_reset_token,
    verify_password_reset_token,
    use_password_reset_token,
    reset_user_password,
    
    # Favorites
    add_favorite,
    remove_favorite,
    get_favorites,
    is_favorited,
    update_favorite_notes,
    
    # Saved searches
    create_saved_search,
    get_saved_searches,
    delete_saved_search,
    update_saved_search_last_run,
    
    # Price alerts
    create_price_alert,
    get_price_alerts,
    delete_price_alert,
    toggle_price_alert,
    update_price_alert_triggered,
    get_active_price_alerts,
    
    # Pagination
    get_listings_paginated,
    
    # Notification preferences
    get_notification_preferences,
    update_notification_preferences,
    get_users_with_notifications_enabled,
    
    # Settings management
    get_settings,
    update_setting,
    
    # User activity
    log_user_activity,
    get_user_activity,
    get_recent_activity,
    
    # Rate limiting
    check_rate_limit,
    reset_rate_limit,
    
    # Listings
    save_listing,
    get_listings,
    get_listing_count,
    
    # Analytics
    save_listing_analytics,
    get_keyword_trends,
    get_price_analytics,
    get_source_comparison,
    get_keyword_analysis,
    get_hourly_activity,
    get_price_distribution,
    update_keyword_trends,
    get_market_insights,
    
    # Seller listings
    create_seller_listing,
    get_seller_listings,
    get_seller_listing_by_id,
    update_seller_listing,
    delete_seller_listing,
    update_seller_listing_urls,
    get_seller_listing_stats,
    
    # Subscription management
    get_user_subscription,
    create_or_update_subscription,
    log_subscription_event,
    get_subscription_history,
    cancel_subscription,
    get_all_subscriptions,
    get_subscription_stats,
    get_subscription_by_customer_id,
    
    # Terms of Service
    record_tos_agreement,

    # Community servers
    create_server,
    get_server_by_id,
    get_server_by_slug,
    get_server_channels,
    create_server_channel,
    get_server_roles,
    get_server_membership,
    get_user_server_permissions,
    is_user_blocked,
    list_user_blocks,
    block_user,
    unblock_user,
    get_server_keyword_filters,
    add_server_keyword_filter,
    remove_server_keyword_filter,
    get_server_analytics,
    get_community_analytics,
    create_server_invite,
    get_server_invite_by_code,
    join_server,
    list_server_pending_requests,
    respond_to_join_request,
    list_user_servers,
    get_all_servers,
    get_server_channel_by_slug,
    get_server_channel,
    get_channel_message,
    get_channel_messages,
    get_channel_message_attachments,
    get_channel_message_reactions,
    add_channel_message_reaction,
    remove_channel_message_reaction,
    create_channel_message,
    discover_servers,
    search_servers,
    get_trending_servers,
    get_recommended_servers,
    log_moderation_action,
    list_moderation_actions,
    get_moderation_actions_export,
    ensure_referral_code,
    create_referral_code,
    get_referral_code,
    get_referral_code_by_code,
    get_referral_overview,
    record_referral_hit,
    redeem_referral_code,
    list_server_tips,
    create_server_tip,
    update_server_tip,
    delete_server_tip,
    dismiss_server_tip,
    get_server_tip,
    get_server_tip_dismissals,
    record_user_engagement,
    get_user_streak,
    create_server_boost_tier,
    list_server_boost_tiers,
    get_server_boost_tier,
    update_server_boost_tier,
    delete_server_boost_tier,
    activate_server_boost,
    get_server_boost,
    list_server_boosts,
    cancel_server_boost,
    get_billing_usage,
    create_report,
    get_report_by_id,
    update_report_status,
    list_reports,
    compute_server_owner_digest,
    get_server_owner_digest_preview,
    enqueue_server_owner_digest,
    list_server_owner_digests,
    get_pending_owner_digests,
    mark_server_owner_digest_delivered,
    get_moderation_keyword_suggestions,
    # Direct messaging
    is_user_in_dm_conversation,
    create_dm_conversation,
    rename_dm_conversation,
    leave_dm_conversation,
    list_dm_conversations,
    get_dm_conversation,
    get_dm_messages,
    create_dm_message,
    update_dm_read_receipt,
    mark_dm_participant_active,
    list_dm_participants,
    # Shared resources
    get_dm_reactions,
    add_dm_message_reaction,
    remove_dm_message_reaction,
    # Feed & notifications
    log_feed_event,
    get_home_feed,
    get_server_feed,
    create_notification,
    get_notifications,
    mark_notifications_seen,
    mark_notifications_read,
    mark_all_notifications_read,
    dismiss_notification,
    get_listing_by_id,
    record_slow_mode_violation,
    get_saved_search_by_id,
)

# Re-export all functions for backward compatibility
__all__ = [
    'init_db',
    'close_database',
    'get_pool',
    'get_user_by_username',
    'get_user_by_email',
    'create_user_db',
    'update_user_login',
    'get_all_users',
    'get_all_user_emails',
    'get_user_count',
    'update_user_role',
    'deactivate_user',
    'get_notification_preferences',
    'update_notification_preferences',
    'get_users_with_notifications_enabled',
    'get_settings',
    'update_setting',
    'log_user_activity',
    'get_user_activity',
    'get_recent_activity',
    'check_rate_limit',
    'reset_rate_limit',
    'create_support_ticket',
    'get_support_ticket',
    'list_support_tickets',
    'add_support_ticket_event',
    'list_support_ticket_events',
    'update_support_ticket',
    'get_support_metrics',
    'export_user_data',
    'purge_user_data',
    'save_listing',
    'get_listings',
    'get_listing_count',
    'save_listing_analytics',
    'get_keyword_trends',
    'get_price_analytics',
    'get_source_comparison',
    'get_keyword_analysis',
    'get_hourly_activity',
    'get_price_distribution',
    'update_keyword_trends',
    'get_market_insights',
    'create_seller_listing',
    'get_seller_listings',
    'get_seller_listing_by_id',
    'update_seller_listing',
    'delete_seller_listing',
    'update_seller_listing_urls',
    'get_seller_listing_stats',
    'get_user_subscription',
    'create_or_update_subscription',
    'log_subscription_event',
    'get_subscription_history',
    'cancel_subscription',
    'get_all_subscriptions',
    'get_subscription_stats',
    'get_subscription_by_customer_id',
    'record_tos_agreement',
    'create_server',
    'get_server_by_id',
    'get_server_by_slug',
    'get_server_channels',
    'create_server_channel',
    'get_server_roles',
    'get_server_membership',
    'get_user_server_permissions',
    'is_user_blocked',
    'list_user_blocks',
    'block_user',
    'unblock_user',
    'get_server_keyword_filters',
    'add_server_keyword_filter',
    'remove_server_keyword_filter',
    'get_server_analytics',
    'get_community_analytics',
    'create_server_invite',
    'get_server_invite_by_code',
    'join_server',
    'list_server_pending_requests',
    'respond_to_join_request',
    'list_user_servers',
    'get_all_servers',
    'get_server_channel_by_slug',
    'get_server_channel',
    'get_channel_message',
    'get_channel_messages',
    'get_channel_message_attachments',
    'get_channel_message_reactions',
    'add_channel_message_reaction',
    'remove_channel_message_reaction',
    'create_channel_message',
    'discover_servers',
    'search_servers',
    'get_trending_servers',
    'get_recommended_servers',
    'log_moderation_action',
    'list_moderation_actions',
    'get_moderation_actions_export',
    'ensure_referral_code',
    'create_referral_code',
    'get_referral_code',
    'get_referral_code_by_code',
    'get_referral_overview',
    'record_referral_hit',
    'redeem_referral_code',
    'list_server_tips',
    'create_server_tip',
    'update_server_tip',
    'delete_server_tip',
    'dismiss_server_tip',
    'get_server_tip',
    'get_server_tip_dismissals',
    'record_user_engagement',
    'get_user_streak',
    'create_server_boost_tier',
    'list_server_boost_tiers',
    'get_server_boost_tier',
    'update_server_boost_tier',
    'delete_server_boost_tier',
    'activate_server_boost',
    'get_server_boost',
    'list_server_boosts',
    'cancel_server_boost',
    'get_billing_usage',
    'create_report',
    'get_report_by_id',
    'update_report_status',
    'list_reports',
    'compute_server_owner_digest',
    'get_server_owner_digest_preview',
    'enqueue_server_owner_digest',
    'list_server_owner_digests',
    'get_pending_owner_digests',
    'mark_server_owner_digest_delivered',
    'get_moderation_keyword_suggestions',
    'create_verification_token',
    'verify_email_token',
    'create_password_reset_token',
    'verify_password_reset_token',
    'use_password_reset_token',
    'reset_user_password',
    'add_favorite',
    'remove_favorite',
    'get_favorites',
    'is_favorited',
    'update_favorite_notes',
    'create_saved_search',
    'get_saved_searches',
    'delete_saved_search',
    'update_saved_search_last_run',
    'create_price_alert',
    'get_price_alerts',
    'delete_price_alert',
    'toggle_price_alert',
    'update_price_alert_triggered',
    'get_active_price_alerts',
    'get_listings_paginated',
    'is_user_in_dm_conversation',
    'create_dm_conversation',
    'list_dm_conversations',
    'rename_dm_conversation',
    'leave_dm_conversation',
    'get_dm_conversation',
    'get_dm_messages',
    'create_dm_message',
    'update_dm_read_receipt',
    'mark_dm_participant_active',
    'list_dm_participants',
    'get_dm_reactions',
    'add_dm_message_reaction',
    'remove_dm_message_reaction',
    'log_feed_event',
    'get_home_feed',
    'get_server_feed',
    'create_notification',
    'get_notifications',
    'mark_notifications_seen',
    'mark_notifications_read',
    'mark_all_notifications_read',
    'dismiss_notification',
    'record_slow_mode_violation',
    'get_listing_by_id',
    'get_saved_search_by_id',
]