services:
  # Web Service Configuration
  - type: web
    name: super-bot
    runtime: python
    plan: starter  # Options: free, starter, standard, pro
    region: oregon  # Options: oregon, ohio, frankfurt, singapore, mumbai, sydney
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:socketio
    envVars:
      # Flask Configuration (REQUIRED - CHANGE SECRET_KEY!)
      - key: SECRET_KEY
        generateValue: true  # Render will auto-generate, but you should set your own
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      
      # Port (Render sets this automatically)
      - key: PORT
        fromService:
          type: web
          name: super-bot
          property: port
      
      # Session Security
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: SESSION_COOKIE_HTTPONLY
        value: "True"
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: PERMANENT_SESSION_LIFETIME
        value: "3600"
      
      # Database
      - key: DB_FILE
        value: superbot.db
      
      # Worker Configuration
      - key: WEB_CONCURRENCY
        value: "2"
      
      # Optional: Add your own environment variables below
      # Uncomment and set your values:
      
      # Email Configuration (if using notifications)
      # - key: SMTP_HOST
      #   value: smtp.gmail.com
      # - key: SMTP_PORT
      #   value: "587"
      # - key: SMTP_USERNAME
      #   value: your-email@gmail.com
      # - key: SMTP_PASSWORD
      #   value: your-app-password
      # - key: SMTP_FROM_EMAIL
      #   value: your-email@gmail.com
      
      # Stripe Configuration (if using payments)
      # - key: STRIPE_SECRET_KEY
      #   value: sk_live_your-key
      # - key: STRIPE_PUBLISHABLE_KEY
      #   value: pk_live_your-key
      # - key: STRIPE_WEBHOOK_SECRET
      #   value: whsec_your-secret
      # - key: STRIPE_STANDARD_PRICE_ID
      #   value: price_your-id
      # - key: STRIPE_PRO_PRICE_ID
      #   value: price_your-id
      
      # Twilio Configuration (if using SMS)
      # - key: TWILIO_ACCOUNT_SID
      #   value: your-sid
      # - key: TWILIO_AUTH_TOKEN
      #   value: your-token
      # - key: TWILIO_FROM_NUMBER
      #   value: +1234567890

# Optional: Add PostgreSQL database for persistent storage
# Uncomment below if you want to use PostgreSQL instead of SQLite
# databases:
#   - name: superbot-db
#     plan: free  # Options: free, starter, standard, pro
#     databaseName: superbot
#     user: superbot

