services:
  - type: web
    name: super-bot
    env: python
    region: oregon
    plan: starter
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn --config gunicorn_config.py app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: False
      - key: SESSION_COOKIE_SECURE
        value: True
      - key: SESSION_COOKIE_HTTPONLY
        value: True
      - key: SESSION_COOKIE_SAMESITE
        value: Lax
      - key: PERMANENT_SESSION_LIFETIME
        value: 3600
      - key: MIN_PASSWORD_LENGTH
        value: 8
      - key: REQUIRE_SPECIAL_CHARS
        value: True
      - key: REQUIRE_NUMBERS
        value: True
      - key: REQUIRE_UPPERCASE
        value: True
      - key: DB_FILE
        value: /opt/render/project/src/superbot.db
      - key: POOL_SIZE
        value: 10
      - key: CONNECTION_TIMEOUT
        value: 30
      - key: RATE_LIMIT_API
        value: 60
      - key: RATE_LIMIT_SCRAPER
        value: 10
      - key: RATE_LIMIT_SETTINGS
        value: 30
      - key: RATE_LIMIT_LOGIN
        value: 5
      - key: RATE_LIMIT_REGISTER
        value: 3
      - key: CACHE_DEFAULT_TTL
        value: 300
      - key: LOG_LEVEL
        value: INFO
      - key: WEB_CONCURRENCY
        value: 2
      # Add these in Render Dashboard - keep these secret!
      # STRIPE_SECRET_KEY
      # STRIPE_PUBLISHABLE_KEY
      # STRIPE_WEBHOOK_SECRET
      # STRIPE_STANDARD_PRICE_ID
      # STRIPE_PRO_PRICE_ID
      # SMTP_HOST
      # SMTP_PORT
      # SMTP_USERNAME
      # SMTP_PASSWORD
      # SMTP_FROM_EMAIL
      # SMTP_FROM_NAME
      # TWILIO_ACCOUNT_SID
      # TWILIO_AUTH_TOKEN
      # TWILIO_FROM_NUMBER

